/*
 * generated by Xtext 2.21.0
 */
package org.example.expressions.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ExpressionsUiModule extends AbstractExpressionsUiModule {

	public ExpressionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
