/*
 * generated by Xtext 2.21.0
 */
package org.example.expressions.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.example.expressions.ExpressionsRuntimeModule;
import org.example.expressions.ExpressionsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ExpressionsIdeSetup extends ExpressionsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ExpressionsRuntimeModule(), new ExpressionsIdeModule()));
	}
	
}
