/*
 * generated by Xtext 2.21.0
 */
package org.example.expressions.ide;


/**
 * Use this class to register ide components.
 */
public class ExpressionsIdeModule extends AbstractExpressionsIdeModule {
}
