/*
 * generated by Xtext 2.21.0
 */
package org.example.expressions.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.example.expressions.ui.internal.ExpressionsActivator;

public class ExpressionsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ExpressionsActivator.getInstance().getInjector("org.example.expressions.Expressions");
	}

}
