/**
 * generated by Xtext 2.21.0
 */
package org.example.expressions.expressions.impl;

import org.eclipse.emf.ecore.EClass;

import org.example.expressions.expressions.EvalExpression;
import org.example.expressions.expressions.ExpressionsPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Eval Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EvalExpressionImpl extends AbstractElementImpl implements EvalExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EvalExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressionsPackage.Literals.EVAL_EXPRESSION;
  }

} //EvalExpressionImpl
