/**
 * generated by Xtext 2.21.0
 */
package org.example.expressions.expressions.impl;

import org.eclipse.emf.ecore.EClass;

import org.example.expressions.expressions.ExpressionsPackage;
import org.example.expressions.expressions.SimplifyExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simplify Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimplifyExpressionImpl extends AbstractElementImpl implements SimplifyExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimplifyExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ExpressionsPackage.Literals.SIMPLIFY_EXPRESSION;
  }

} //SimplifyExpressionImpl
