/**
 * generated by Xtext 2.21.0
 */
package org.example.expressions.expressions;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Eval Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.example.expressions.expressions.ExpressionsPackage#getEvalExpression()
 * @model
 * @generated
 */
public interface EvalExpression extends AbstractElement
{
} // EvalExpression
