/*
 * generated by Xtext 2.21.0
 */
package org.example.expressions.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.example.expressions.ui.internal.ExpressionsActivator;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ExpressionsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ExpressionsActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ExpressionsActivator activator = ExpressionsActivator.getInstance();
		return activator != null ? activator.getInjector(ExpressionsActivator.ORG_EXAMPLE_EXPRESSIONS_EXPRESSIONS) : null;
	}

}
