/*
 * generated by Xtext 2.21.0
 */
package org.example.expressions.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExpressionsScopeProvider extends DelegatingScopeProvider {
}
